---
title: "Variant Processing"
author: "BF"
date: "2024-07-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
# Load required library
library(readxl)

# Specify the path to the Excel file
file_path <- "//Users/benfixman/Library/Mobile Documents/com~apple~CloudDocs/Chen_Lab/RNA_SBS/APOBEC3A cytidine deaminase induces RNA editing in monocytes and macrophages/Data/variants/polarization_variants_updated-selected-columns.xlsx"

# Read in the Excel file
data <- read_excel(file_path)

# Add "chr" before every value in the chr column
data$chr <- paste0("chr", data$chr)

# Fill "Hypoxia" in every cell in the sample_id column
data$sample_id <- "Polarization"

# Create the muttype column by adding ref and alt alleles
data$muttype <- paste(data$Ref, data$Alt, sep=">")

# Replace U with T in muttype column (if necessary, depending on your data)
data$muttype <- gsub("U", "T", data$muttype)

# Filter rows with positive Log2FoldChangeBaseAlterationIBB values
data <- data[data$Log2FoldChangeBaseAlterationIBB > 0, ]

# Remove Ref, Alt, and Log2FoldC columns (assuming these are the columns you want to remove)
data <- data[, !(names(data) %in% c("Ref", "Alt", "Log2FoldChangeBaseAlterationIBB"))]

# Write the updated data to a CSV file
write.csv(data, "/Users/benfixman/Library/Mobile Documents/com~apple~CloudDocs/Chen_Lab/RNA_SBS/APOBEC3A cytidine deaminase induces RNA editing in monocytes and macrophages/Data/variants/polarization-variants_updated.csv", row.names = FALSE)
```


